// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOp7Cz3nxU3bnFAdd7pb1YxolceK2C9Fg',
    appId: '1:6968629674:web:3905e171168147948433d3',
    messagingSenderId: '6968629674',
    projectId: 'weatherai-a5b44',
    authDomain: 'weatherai-a5b44.firebaseapp.com',
    storageBucket: 'weatherai-a5b44.firebasestorage.app',
    measurementId: 'G-WPVH2S1EMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR1KM5_RMHte_VgSUUp5cYtL2wHWaITa0',
    appId: '1:6968629674:android:293e031b9d8838458433d3',
    messagingSenderId: '6968629674',
    projectId: 'weatherai-a5b44',
    storageBucket: 'weatherai-a5b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuSMPWYEUp_LEsc4a7xfrOMIm78PCL1Js',
    appId: '1:6968629674:ios:af0d640130fc4bb08433d3',
    messagingSenderId: '6968629674',
    projectId: 'weatherai-a5b44',
    storageBucket: 'weatherai-a5b44.firebasestorage.app',
    iosBundleId: 'com.example.aiweather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuSMPWYEUp_LEsc4a7xfrOMIm78PCL1Js',
    appId: '1:6968629674:ios:af0d640130fc4bb08433d3',
    messagingSenderId: '6968629674',
    projectId: 'weatherai-a5b44',
    storageBucket: 'weatherai-a5b44.firebasestorage.app',
    iosBundleId: 'com.example.aiweather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOp7Cz3nxU3bnFAdd7pb1YxolceK2C9Fg',
    appId: '1:6968629674:web:425f188d2176f0678433d3',
    messagingSenderId: '6968629674',
    projectId: 'weatherai-a5b44',
    authDomain: 'weatherai-a5b44.firebaseapp.com',
    storageBucket: 'weatherai-a5b44.firebasestorage.app',
    measurementId: 'G-VQRPRBTB9X',
  );
}
